"""empty message

Revision ID: 65873132e7f1
Revises: 0763d677d453
Create Date: 2026-01-28 16:11:27.241045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65873132e7f1'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
